### ISSUE TITLE
Task.17 - Create a course creation page where course details can be specified

### ISSUE THREAD

**Issue by sasha-klnd** [Vinuyans/Mega_Chug_Lords-SOEN341_Project_F24#17] opened 2024-09-19 23:37 UTC
Create a page for course creation where the teacher can enter the following details:
 - course title
 - course code
 - maximum participants
 - semester offered"

**Comment by Vinuyans** [comment] 2024-11-11 00:22
Duplicate of #43

**Closed as not planned by Vinuyans** 2024-11-11 00:22 UTC
Labels: duplicate, Frontend, Features
